<?php
function calculateCurrency($fromCurrency, $toCurrency, $amount) {
    $amount = urlencode($amount);
    $fromCurrency = urlencode($fromCurrency);
    $toCurrency = urlencode($toCurrency);
    $rawdata = file_get_contents("https://finance.google.com/finance/converter?a=$amount&from=$fromCurrency&to=$toCurrency");

    $data = explode('bld>', $rawdata);
    $data = explode($toCurrency, $data[1]);
    return round($data[0],2) ;
}
if($_REQUEST['submit'])
{
	if(!empty($_REQUEST['currencyamount']) && !empty($_REQUEST['currencyfrom']) && !empty($_REQUEST['currencyto']))
	{
		//echo calculateCurrency('USD','INR',1);  
		$converted_amount=calculateCurrency($_REQUEST['currencyfrom'],$_REQUEST['currencyto'],$_REQUEST['currencyamount']);
		echo "<h1>Converted Amount : $converted_amount </h1>";		
		   
	}
	else
	{
		echo 'Please enter all fields';
	}
 
}
?>

<form method="POST">
<table border="0" cellpadding="2" cellspacing="0" summary=""><tr><td>
Amount:</td><td><input type="text" size="8" name="currencyamount">
</td></tr><tr><td>
From:
</td><td>
<select name="currencyfrom">
<option value="" selected>Select a currency</option>
<option value="ZRX">0x (ZRX)</option>
<option value="AFN">Afghan Afghani (AFN)</option>
<option value="ALL">Albanian Lek (ALL)</option>
<option value="DZD">Algerian Dinar (DZD)</option>
<option value="AOA">Angolan Kwanza (AOA)</option>
<option value="ANC">Anoncoin (ANC)</option>
<option value="ARDR">Ardor (ARDR)</option>
<option value="ARS">Argentine Peso (ARS)</option>
<option value="ARG">Argentum (ARG)</option>
<option value="AMD">Armenian Dram (AMD)</option>
<option value="AWG">Aruban Florin (AWG)</option>
<option value="REP">Augur (REP)</option>
<option value="AUR">Auroracoin (AUR)</option>
<option value="AUD">Australian Dollar (AUD)</option>
<option value="AZN">Azerbaijani Manat (AZN)</option>
<option value="BSD">Bahamian Dollar (BSD)</option>
<option value="BHD">Bahraini Dinar (BHD)</option>
<option value="BDT">Bangladeshi Taka (BDT)</option>
<option value="BBD">Barbados Dollar (BBD)</option>
<option value="BYN">Belarusian Ruble (BYN)</option>
<option value="BZD">Belize Dollar (BZD)</option>
<option value="BMD">Bermuda Dollar (BMD)</option>
<option value="BET">BetaCoin (BET)</option>
<option value="BTN">Bhutanese Ngultrum (BTN)</option>
<option value="BNB">Binance Coin (BNB)</option>
<option value="BTB">BitBar (BTB)</option>
<option value="BTS">BitShare (BTS)</option>
<option value="BTC">Bitcoin (BTC)</option>
<option value="BCH">Bitcoin Cash (BCH)</option>
<option value="BTG">Bitcoin Gold (BTG)</option>
<option value="XMR">Bitmonero (XMR)</option>
<option value="BLC">BlackCoin (BLC)</option>
<option value="BOB">Bolivian Boliviano (BOB)</option>
<option value="BAM">Bosnia-Herzegovina Convertible Mark (BAM)</option>
<option value="BWP">Botswana Pula (BWP)</option>
<option value="BRL">Brazilian Real (BRL)</option>
<option value="BND">Brunei Dollar (BND)</option>
<option value="BGN">Bulgarian Lev (BGN)</option>
<option value="BIF">Burundian Franc (BIF)</option>
<option value="BCN">Bytecoin (BCN) (BCN)</option>
<option value="KHR">Cambodian Riel (KHR)</option>
<option value="CAD">Canadian Dollar (CAD)</option>
<option value="CVE">Cape Verde Escudo (CVE)</option>
<option value="ADA">Cardano (ADA)</option>
<option value="KYD">Cayman Islands Dollar (KYD)</option>
<option value="XAF">Central African CFA (XAF)</option>
<option value="CLP">Chilean Peso (CLP)</option>
<option value="CLF">Chilean Unidad de Fomento (CLF)</option>
<option value="CNH">Chinese Offshore Yuan (CNH)</option>
<option value="CNY">Chinese Yuan (CNY)</option>
<option value="COP">Colombian Peso (COP)</option>
<option value="KMF">Comorian Franc (KMF)</option>
<option value="CRC">Costa Rican Colon (CRC)</option>
<option value="ZCP">Counterparty (ZCP)</option>
<option value="XCC">CraftCoin (XCC)</option>
<option value="HRK">Croatian Kuna (HRK)</option>
<option value="CUC">Cuban Convertible Peso (CUC)</option>
<option value="CYP">Cypriot Pound (CYP)</option>
<option value="CZK">Czech Koruna (CZK)</option>
<option value="DKK">Danish Krone (DKK)</option>
<option value="DASH">Dash (DASH)</option>
<option value="DEE">Deutsche eMark (DEE)</option>
<option value="DMD">DiamondCoins (DMD)</option>
<option value="DGC">Digitalcoin (DGC)</option>
<option value="DJF">Djiboutian Franc (DJF)</option>
<option value="XDG">DogeCoin (XDG)</option>
<option value="DOP">Dominican Peso (DOP)</option>
<option value="EOS">EOS (EOS)</option>
<option value="XCD">East Caribbean Dollar (XCD)</option>
<option value="EGP">Egyptian Pound (EGP)</option>
<option value="EFL">Electronic Gulden (EFL)</option>
<option value="ERN">Eritrean Nakfa (ERN)</option>
<option value="ETH">Ethereum (ETH)</option>
<option value="ETC">Ethereum Classic (ETC)</option>
<option value="ETB">Ethiopian Birr (ETB)</option>
<option value="EUR">Euro (EUR)</option>
<option value="FKP">Falkland Islands Pound (FKP)</option>
<option value="FST">Fastcoin (FST)</option>
<option value="FTC">Feathercoin (FTC)</option>
<option value="FJD">Fiji Dollar (FJD)</option>
<option value="FLO">FlorinCoin (FLO)</option>
<option value="FLT">FlutterCoin (FLT)</option>
<option value="CDF">Franc Congolais (CDF)</option>
<option value="FRK">Franko (FRK)</option>
<option value="FRC">Freicoin (FRC)</option>
<option value="XPF">French Pacific Franc (XPF)</option>
<option value="GMD">Gambian Dalasi (GMD)</option>
<option value="GEL">Georgian Lari (GEL)</option>
<option value="GHS">Ghanaian Cedi (GHS)</option>
<option value="GIP">Gibraltar Pound (GIP)</option>
<option value="GLC">GlobalCoin (GLC)</option>
<option value="GLD">GoldCoin (GLD)</option>
<option value="GTQ">Guatemalan Quetzal (GTQ)</option>
<option value="GNF">Guinean Franc (GNF)</option>
<option value="GYD">Guyanese Dollar (GYD)</option>
<option value="HTG">Haitian Gourde (HTG)</option>
<option value="HBN">HoboNickel (HBN)</option>
<option value="HNL">Honduran Lempira (HNL)</option>
<option value="HKD">Hong Kong Dollar (HKD)</option>
<option value="HUF">Hungarian Forint (HUF)</option>
<option value="XIC">I0Coin (XIC)</option>
<option value="ICX">ICON (ICX)</option>
<option value="MIOTA">IOTA (MIOTA)</option>
<option value="ISK">Icelandic Krona (ISK)</option>
<option value="INR">Indian Rupee (INR)</option>
<option value="IDR">Indonesian Rupiah (IDR)</option>
<option value="IRR">Iranian Rial (IRR)</option>
<option value="IQD">Iraqi Dinar (IQD)</option>
<option value="ILS">Israeli New Shekel (ILS)</option>
<option value="IXC">Ixcoin (IXC)</option>
<option value="JMD">Jamaican Dollar (JMD)</option>
<option value="JPY">Japanese Yen (JPY)</option>
<option value="JEP">Jersey Pound (JEP)</option>
<option value="JOD">Jordanian Dinar (JOD)</option>
<option value="XJO">Joulecoin (XJO)</option>
<option value="KZT">Kazakhstani Tenge (KZT)</option>
<option value="KES">Kenyan Shilling (KES)</option>
<option value="KRW">Korean Won (KRW)</option>
<option value="KWD">Kuwaiti Dinar (KWD)</option>
<option value="KGS">Kyrgyzstani Som (KGS)</option>
<option value="LAK">Lao Kip (LAK)</option>
<option value="LBP">Lebanese Pound (LBP)</option>
<option value="LSL">Lesotho Loti (LSL)</option>
<option value="LRD">Liberian Dollar (LRD)</option>
<option value="LYD">Libyan Dinar (LYD)</option>
<option value="LSK">Lisk (LSK)</option>
<option value="LTC">Litecoin (LTC)</option>
<option value="LTL">Lithuanian Litas (LTL)</option>
<option value="MOP">Macau Pataca (MOP)</option>
<option value="MKD">Macedonia Denar (MKD)</option>
<option value="XMS">MaidSafeCoin (XMS)</option>
<option value="MKR">Maker (MKR)</option>
<option value="MGA">Malagasy Ariary (MGA)</option>
<option value="MWK">Malawian Kwacha (MWK)</option>
<option value="MYR">Malaysian Ringgit (MYR)</option>
<option value="MVR">Maldives Rufiyaa (MVR)</option>
<option value="MRO">Mauritania Ouguiya (MRO)</option>
<option value="MUR">Mauritian Rupee (MUR)</option>
<option value="MAX">MaxCoin (MAX)</option>
<option value="MEC">Megacoin (MEC)</option>
<option value="MXN">Mexican Peso (MXN)</option>
<option value="MXV">Mexican Unidad De Inversion (MXV)</option>
<option value="MNC">Mincoin (MNC)</option>
<option value="XMT">Mintcoin (XMT)</option>
<option value="MDL">Moldovan Leu (MDL)</option>
<option value="MNT">Mongolian Tugrik (MNT)</option>
<option value="MAD">Moroccan Dirham (MAD)</option>
<option value="MMK">Myanmar Kyat (MMK)</option>
<option value="XEM">NEM (XEM)</option>
<option value="NEO">NEO (NEO)</option>
<option value="NMC">Namecoin (NMC)</option>
<option value="NAD">Namibian Dollar (NAD)</option>
<option value="NAS">Nas (NAS)</option>
<option value="NPR">Nepalese Rupee (NPR)</option>
<option value="NET">NetCoin (NET)</option>
<option value="ANG">Netherlands Antillean Guilder (ANG)</option>
<option value="MZN">New Mozambican Metical (MZN)</option>
<option value="TWD">New Taiwan Dollar (TWD)</option>
<option value="NZD">New Zealand Dollar (NZD)</option>
<option value="NIO">Nicaraguan Cordoba Oro (NIO)</option>
<option value="NGN">Nigerian Naira (NGN)</option>
<option value="KPW">North Korean Won (KPW)</option>
<option value="NOK">Norwegian Krone (NOK)</option>
<option value="NVC">Novacoin (NVC)</option>
<option value="NXT">Nxt (NXT)</option>
<option value="OMR">Omani Rial (OMR)</option>
<option value="OMG">OmiseGO (OMG)</option>
<option value="ORB">Orbitcoin (ORB)</option>
<option value="XAL">Ounces of Aluminum (XAL)</option>
<option value="XCP">Ounces of Copper (XCP)</option>
<option value="XAU">Ounces of Gold (XAU)</option>
<option value="XPD">Ounces of Palladium (XPD)</option>
<option value="XPT">Ounces of Platinum (XPT)</option>
<option value="XAG">Ounces of Silver (XAG)</option>
<option value="PKR">Pakistan Rupee (PKR)</option>
<option value="PAB">Panamanian Balboa (PAB)</option>
<option value="PGK">Papua New Guinea Kina (PGK)</option>
<option value="PYG">Paraguay Guarani (PYG)</option>
<option value="PPC">Peercoin (PPC)</option>
<option value="PEN">Peruvian Nuevo Sol (PEN)</option>
<option value="PTC">Pesetacoin (PTC)</option>
<option value="PHP">Philippine Peso (PHP)</option>
<option value="PHS">Philosopher Stones (PHS)</option>
<option value="PXC">Phoenixcoin (PXC)</option>
<option value="PLN">Polish Zloty (PLN)</option>
<option value="PPT">Populous (PPT)</option>
<option value="POT">PotCoin (POT)</option>
<option value="GBP">Pound Sterling (GBP)</option>
<option value="XPM">Primecoin (XPM)</option>
<option value="QAR">Qatari Riyal (QAR)</option>
<option value="QTUM">Qtum (QTUM)</option>
<option value="QRK">QuarkCoin (QRK)</option>
<option value="XRB">RaiBlocs (XRB)</option>
<option value="RDD">ReddCoin (RDD)</option>
<option value="XRP">Ripple (XRP)</option>
<option value="RON">Romanian Leu (RON)</option>
<option value="RUB">Russian Ruble (RUB)</option>
<option value="RWF">Rwandan Franc (RWF)</option>
<option value="SHP">Saint Helena Pound (SHP)</option>
<option value="WST">Samoa Tala (WST)</option>
<option value="STD">Sao Tome Dobra (STD)</option>
<option value="SAR">Saudi Arabian Riyal (SAR)</option>
<option value="RSD">Serbian Dinar (RSD)</option>
<option value="SXC">Sexcoin (SXC)</option>
<option value="SCR">Seychelles Rupee (SCR)</option>
<option value="XSC">Siacoin (XSC)</option>
<option value="SLL">Sierra Leonean Leone (SLL)</option>
<option value="SGD">Singapore Dollar (SGD)</option>
<option value="SLR">SolarCoin (SLR)</option>
<option value="SBD">Solomon Islands Dollar (SBD)</option>
<option value="SOS">Somali Shilling (SOS)</option>
<option value="ZAR">South African Rand (ZAR)</option>
<option value="SDR">Special Drawing Right (SDR)</option>
<option value="LKR">Sri Lankan Rupee (LKR)</option>
<option value="SNT">Status (SNT)</option>
<option value="STEEM">Steem (STEEM)</option>
<option value="XLM">Stellar (XLM)</option>
<option value="STRAT">Stratis (STRAT)</option>
<option value="SDG">Sudanese Pound (SDG)</option>
<option value="SRD">Suriname Dollar (SRD)</option>
<option value="SZL">Swazi Lilangeni (SZL)</option>
<option value="SEK">Swedish Krona (SEK)</option>
<option value="CHF">Swiss Franc (CHF)</option>
<option value="SYP">Syrian Pound (SYP)</option>
<option value="TRX">TRON (TRX)</option>
<option value="TAG">TagCoin (TAG)</option>
<option value="TJS">Tajikistan Somoni (TJS)</option>
<option value="TZS">Tanzanian Shilling (TZS)</option>
<option value="TRC">Terracoin (TRC)</option>
<option value="USDT">Tether (USDT)</option>
<option value="THB">Thai Baht (THB)</option>
<option value="TIX">Tickets (TIX)</option>
<option value="TGC">Tigercoin (TGC)</option>
<option value="TOP">Tongan Pa'Anga (TOP)</option>
<option value="TTD">Trinidad and Tobago Dollar (TTD)</option>
<option value="TND">Tunisian Dinar (TND)</option>
<option value="TRY">Turkish Lira (TRY)</option>
<option value="TMT">Turkmenistan Manat (TMT)</option>
<option value="UGX">Uganda Shilling (UGX)</option>
<option value="UAH">Ukrainian Hryvnia (UAH)</option>
<option value="AED">United Arab Emirates Dirham (AED)</option>
<option value="USD">United States Dollar (USD)</option>
<option value="UNO">Unobtanium (UNO)</option>
<option value="UYU">Uruguayan peso (UYU)</option>
<option value="UZS">Uzbekistani Som (UZS)</option>
<option value="VUV">Vanuatu Vatu (VUV)</option>
<option value="VEN">VeChain (VEN)</option>
<option value="VEF">Venezuelan Bolivar Fuerte (VEF)</option>
<option value="XVG">Verge (XVG)</option>
<option value="VRC">VeriCoin (VRC)</option>
<option value="VERI">Veritaseum (VERI)</option>
<option value="VTC">Vertcoin (VTC)</option>
<option value="VND">Viet Nam Dong (VND)</option>
<option value="WTC">Walton (WTC)</option>
<option value="XOF">West African CFA (XOF)</option>
<option value="WDC">WorldCoin (WDC)</option>
<option value="YAC">Yacoin (YAC)</option>
<option value="YER">Yemeni Rial (YER)</option>
<option value="ZMW">Zambian Kwacha (ZMW)</option>
<option value="ZEC">Zcash (ZEC)</option>
<option value="ZTC">Zeitcoin (ZTC)</option>
<option value="ZET">Zetacoin (ZET)</option>
</select>
</td></tr><tr><td>
To:
</td><td>
<select name="currencyto">
<option value="" selected>All other currencies</option>
<option value="ZRX">0x (ZRX)</option>
<option value="AFN">Afghan Afghani (AFN)</option>
<option value="ALL">Albanian Lek (ALL)</option>
<option value="DZD">Algerian Dinar (DZD)</option>
<option value="AOA">Angolan Kwanza (AOA)</option>
<option value="ANC">Anoncoin (ANC)</option>
<option value="ARDR">Ardor (ARDR)</option>
<option value="ARS">Argentine Peso (ARS)</option>
<option value="ARG">Argentum (ARG)</option>
<option value="AMD">Armenian Dram (AMD)</option>
<option value="AWG">Aruban Florin (AWG)</option>
<option value="REP">Augur (REP)</option>
<option value="AUR">Auroracoin (AUR)</option>
<option value="AUD">Australian Dollar (AUD)</option>
<option value="AZN">Azerbaijani Manat (AZN)</option>
<option value="BSD">Bahamian Dollar (BSD)</option>
<option value="BHD">Bahraini Dinar (BHD)</option>
<option value="BDT">Bangladeshi Taka (BDT)</option>
<option value="BBD">Barbados Dollar (BBD)</option>
<option value="BYN">Belarusian Ruble (BYN)</option>
<option value="BZD">Belize Dollar (BZD)</option>
<option value="BMD">Bermuda Dollar (BMD)</option>
<option value="BET">BetaCoin (BET)</option>
<option value="BTN">Bhutanese Ngultrum (BTN)</option>
<option value="BNB">Binance Coin (BNB)</option>
<option value="BTB">BitBar (BTB)</option>
<option value="BTS">BitShare (BTS)</option>
<option value="BTC">Bitcoin (BTC)</option>
<option value="BCH">Bitcoin Cash (BCH)</option>
<option value="BTG">Bitcoin Gold (BTG)</option>
<option value="XMR">Bitmonero (XMR)</option>
<option value="BLC">BlackCoin (BLC)</option>
<option value="BOB">Bolivian Boliviano (BOB)</option>
<option value="BAM">Bosnia-Herzegovina Convertible Mark (BAM)</option>
<option value="BWP">Botswana Pula (BWP)</option>
<option value="BRL">Brazilian Real (BRL)</option>
<option value="BND">Brunei Dollar (BND)</option>
<option value="BGN">Bulgarian Lev (BGN)</option>
<option value="BIF">Burundian Franc (BIF)</option>
<option value="BCN">Bytecoin (BCN) (BCN)</option>
<option value="KHR">Cambodian Riel (KHR)</option>
<option value="CAD">Canadian Dollar (CAD)</option>
<option value="CVE">Cape Verde Escudo (CVE)</option>
<option value="ADA">Cardano (ADA)</option>
<option value="KYD">Cayman Islands Dollar (KYD)</option>
<option value="XAF">Central African CFA (XAF)</option>
<option value="CLP">Chilean Peso (CLP)</option>
<option value="CLF">Chilean Unidad de Fomento (CLF)</option>
<option value="CNH">Chinese Offshore Yuan (CNH)</option>
<option value="CNY">Chinese Yuan (CNY)</option>
<option value="COP">Colombian Peso (COP)</option>
<option value="KMF">Comorian Franc (KMF)</option>
<option value="CRC">Costa Rican Colon (CRC)</option>
<option value="ZCP">Counterparty (ZCP)</option>
<option value="XCC">CraftCoin (XCC)</option>
<option value="HRK">Croatian Kuna (HRK)</option>
<option value="CUC">Cuban Convertible Peso (CUC)</option>
<option value="CYP">Cypriot Pound (CYP)</option>
<option value="CZK">Czech Koruna (CZK)</option>
<option value="DKK">Danish Krone (DKK)</option>
<option value="DASH">Dash (DASH)</option>
<option value="DEE">Deutsche eMark (DEE)</option>
<option value="DMD">DiamondCoins (DMD)</option>
<option value="DGC">Digitalcoin (DGC)</option>
<option value="DJF">Djiboutian Franc (DJF)</option>
<option value="XDG">DogeCoin (XDG)</option>
<option value="DOP">Dominican Peso (DOP)</option>
<option value="EOS">EOS (EOS)</option>
<option value="XCD">East Caribbean Dollar (XCD)</option>
<option value="EGP">Egyptian Pound (EGP)</option>
<option value="EFL">Electronic Gulden (EFL)</option>
<option value="ERN">Eritrean Nakfa (ERN)</option>
<option value="ETH">Ethereum (ETH)</option>
<option value="ETC">Ethereum Classic (ETC)</option>
<option value="ETB">Ethiopian Birr (ETB)</option>
<option value="EUR">Euro (EUR)</option>
<option value="FKP">Falkland Islands Pound (FKP)</option>
<option value="FST">Fastcoin (FST)</option>
<option value="FTC">Feathercoin (FTC)</option>
<option value="FJD">Fiji Dollar (FJD)</option>
<option value="FLO">FlorinCoin (FLO)</option>
<option value="FLT">FlutterCoin (FLT)</option>
<option value="CDF">Franc Congolais (CDF)</option>
<option value="FRK">Franko (FRK)</option>
<option value="FRC">Freicoin (FRC)</option>
<option value="XPF">French Pacific Franc (XPF)</option>
<option value="GMD">Gambian Dalasi (GMD)</option>
<option value="GEL">Georgian Lari (GEL)</option>
<option value="GHS">Ghanaian Cedi (GHS)</option>
<option value="GIP">Gibraltar Pound (GIP)</option>
<option value="GLC">GlobalCoin (GLC)</option>
<option value="GLD">GoldCoin (GLD)</option>
<option value="GTQ">Guatemalan Quetzal (GTQ)</option>
<option value="GNF">Guinean Franc (GNF)</option>
<option value="GYD">Guyanese Dollar (GYD)</option>
<option value="HTG">Haitian Gourde (HTG)</option>
<option value="HBN">HoboNickel (HBN)</option>
<option value="HNL">Honduran Lempira (HNL)</option>
<option value="HKD">Hong Kong Dollar (HKD)</option>
<option value="HUF">Hungarian Forint (HUF)</option>
<option value="XIC">I0Coin (XIC)</option>
<option value="ICX">ICON (ICX)</option>
<option value="MIOTA">IOTA (MIOTA)</option>
<option value="ISK">Icelandic Krona (ISK)</option>
<option value="INR">Indian Rupee (INR)</option>
<option value="IDR">Indonesian Rupiah (IDR)</option>
<option value="IRR">Iranian Rial (IRR)</option>
<option value="IQD">Iraqi Dinar (IQD)</option>
<option value="ILS">Israeli New Shekel (ILS)</option>
<option value="IXC">Ixcoin (IXC)</option>
<option value="JMD">Jamaican Dollar (JMD)</option>
<option value="JPY">Japanese Yen (JPY)</option>
<option value="JEP">Jersey Pound (JEP)</option>
<option value="JOD">Jordanian Dinar (JOD)</option>
<option value="XJO">Joulecoin (XJO)</option>
<option value="KZT">Kazakhstani Tenge (KZT)</option>
<option value="KES">Kenyan Shilling (KES)</option>
<option value="KRW">Korean Won (KRW)</option>
<option value="KWD">Kuwaiti Dinar (KWD)</option>
<option value="KGS">Kyrgyzstani Som (KGS)</option>
<option value="LAK">Lao Kip (LAK)</option>
<option value="LBP">Lebanese Pound (LBP)</option>
<option value="LSL">Lesotho Loti (LSL)</option>
<option value="LRD">Liberian Dollar (LRD)</option>
<option value="LYD">Libyan Dinar (LYD)</option>
<option value="LSK">Lisk (LSK)</option>
<option value="LTC">Litecoin (LTC)</option>
<option value="LTL">Lithuanian Litas (LTL)</option>
<option value="MOP">Macau Pataca (MOP)</option>
<option value="MKD">Macedonia Denar (MKD)</option>
<option value="XMS">MaidSafeCoin (XMS)</option>
<option value="MKR">Maker (MKR)</option>
<option value="MGA">Malagasy Ariary (MGA)</option>
<option value="MWK">Malawian Kwacha (MWK)</option>
<option value="MYR">Malaysian Ringgit (MYR)</option>
<option value="MVR">Maldives Rufiyaa (MVR)</option>
<option value="MRO">Mauritania Ouguiya (MRO)</option>
<option value="MUR">Mauritian Rupee (MUR)</option>
<option value="MAX">MaxCoin (MAX)</option>
<option value="MEC">Megacoin (MEC)</option>
<option value="MXN">Mexican Peso (MXN)</option>
<option value="MXV">Mexican Unidad De Inversion (MXV)</option>
<option value="MNC">Mincoin (MNC)</option>
<option value="XMT">Mintcoin (XMT)</option>
<option value="MDL">Moldovan Leu (MDL)</option>
<option value="MNT">Mongolian Tugrik (MNT)</option>
<option value="MAD">Moroccan Dirham (MAD)</option>
<option value="MMK">Myanmar Kyat (MMK)</option>
<option value="XEM">NEM (XEM)</option>
<option value="NEO">NEO (NEO)</option>
<option value="NMC">Namecoin (NMC)</option>
<option value="NAD">Namibian Dollar (NAD)</option>
<option value="NAS">Nas (NAS)</option>
<option value="NPR">Nepalese Rupee (NPR)</option>
<option value="NET">NetCoin (NET)</option>
<option value="ANG">Netherlands Antillean Guilder (ANG)</option>
<option value="MZN">New Mozambican Metical (MZN)</option>
<option value="TWD">New Taiwan Dollar (TWD)</option>
<option value="NZD">New Zealand Dollar (NZD)</option>
<option value="NIO">Nicaraguan Cordoba Oro (NIO)</option>
<option value="NGN">Nigerian Naira (NGN)</option>
<option value="KPW">North Korean Won (KPW)</option>
<option value="NOK">Norwegian Krone (NOK)</option>
<option value="NVC">Novacoin (NVC)</option>
<option value="NXT">Nxt (NXT)</option>
<option value="OMR">Omani Rial (OMR)</option>
<option value="OMG">OmiseGO (OMG)</option>
<option value="ORB">Orbitcoin (ORB)</option>
<option value="XAL">Ounces of Aluminum (XAL)</option>
<option value="XCP">Ounces of Copper (XCP)</option>
<option value="XAU">Ounces of Gold (XAU)</option>
<option value="XPD">Ounces of Palladium (XPD)</option>
<option value="XPT">Ounces of Platinum (XPT)</option>
<option value="XAG">Ounces of Silver (XAG)</option>
<option value="PKR">Pakistan Rupee (PKR)</option>
<option value="PAB">Panamanian Balboa (PAB)</option>
<option value="PGK">Papua New Guinea Kina (PGK)</option>
<option value="PYG">Paraguay Guarani (PYG)</option>
<option value="PPC">Peercoin (PPC)</option>
<option value="PEN">Peruvian Nuevo Sol (PEN)</option>
<option value="PTC">Pesetacoin (PTC)</option>
<option value="PHP">Philippine Peso (PHP)</option>
<option value="PHS">Philosopher Stones (PHS)</option>
<option value="PXC">Phoenixcoin (PXC)</option>
<option value="PLN">Polish Zloty (PLN)</option>
<option value="PPT">Populous (PPT)</option>
<option value="POT">PotCoin (POT)</option>
<option value="GBP">Pound Sterling (GBP)</option>
<option value="XPM">Primecoin (XPM)</option>
<option value="QAR">Qatari Riyal (QAR)</option>
<option value="QTUM">Qtum (QTUM)</option>
<option value="QRK">QuarkCoin (QRK)</option>
<option value="XRB">RaiBlocs (XRB)</option>
<option value="RDD">ReddCoin (RDD)</option>
<option value="XRP">Ripple (XRP)</option>
<option value="RON">Romanian Leu (RON)</option>
<option value="RUB">Russian Ruble (RUB)</option>
<option value="RWF">Rwandan Franc (RWF)</option>
<option value="SHP">Saint Helena Pound (SHP)</option>
<option value="WST">Samoa Tala (WST)</option>
<option value="STD">Sao Tome Dobra (STD)</option>
<option value="SAR">Saudi Arabian Riyal (SAR)</option>
<option value="RSD">Serbian Dinar (RSD)</option>
<option value="SXC">Sexcoin (SXC)</option>
<option value="SCR">Seychelles Rupee (SCR)</option>
<option value="XSC">Siacoin (XSC)</option>
<option value="SLL">Sierra Leonean Leone (SLL)</option>
<option value="SGD">Singapore Dollar (SGD)</option>
<option value="SLR">SolarCoin (SLR)</option>
<option value="SBD">Solomon Islands Dollar (SBD)</option>
<option value="SOS">Somali Shilling (SOS)</option>
<option value="ZAR">South African Rand (ZAR)</option>
<option value="SDR">Special Drawing Right (SDR)</option>
<option value="LKR">Sri Lankan Rupee (LKR)</option>
<option value="SNT">Status (SNT)</option>
<option value="STEEM">Steem (STEEM)</option>
<option value="XLM">Stellar (XLM)</option>
<option value="STRAT">Stratis (STRAT)</option>
<option value="SDG">Sudanese Pound (SDG)</option>
<option value="SRD">Suriname Dollar (SRD)</option>
<option value="SZL">Swazi Lilangeni (SZL)</option>
<option value="SEK">Swedish Krona (SEK)</option>
<option value="CHF">Swiss Franc (CHF)</option>
<option value="SYP">Syrian Pound (SYP)</option>
<option value="TRX">TRON (TRX)</option>
<option value="TAG">TagCoin (TAG)</option>
<option value="TJS">Tajikistan Somoni (TJS)</option>
<option value="TZS">Tanzanian Shilling (TZS)</option>
<option value="TRC">Terracoin (TRC)</option>
<option value="USDT">Tether (USDT)</option>
<option value="THB">Thai Baht (THB)</option>
<option value="TIX">Tickets (TIX)</option>
<option value="TGC">Tigercoin (TGC)</option>
<option value="TOP">Tongan Pa'Anga (TOP)</option>
<option value="TTD">Trinidad and Tobago Dollar (TTD)</option>
<option value="TND">Tunisian Dinar (TND)</option>
<option value="TRY">Turkish Lira (TRY)</option>
<option value="TMT">Turkmenistan Manat (TMT)</option>
<option value="UGX">Uganda Shilling (UGX)</option>
<option value="UAH">Ukrainian Hryvnia (UAH)</option>
<option value="AED">United Arab Emirates Dirham (AED)</option>
<option value="USD">United States Dollar (USD)</option>
<option value="UNO">Unobtanium (UNO)</option>
<option value="UYU">Uruguayan peso (UYU)</option>
<option value="UZS">Uzbekistani Som (UZS)</option>
<option value="VUV">Vanuatu Vatu (VUV)</option>
<option value="VEN">VeChain (VEN)</option>
<option value="VEF">Venezuelan Bolivar Fuerte (VEF)</option>
<option value="XVG">Verge (XVG)</option>
<option value="VRC">VeriCoin (VRC)</option>
<option value="VERI">Veritaseum (VERI)</option>
<option value="VTC">Vertcoin (VTC)</option>
<option value="VND">Viet Nam Dong (VND)</option>
<option value="WTC">Walton (WTC)</option>
<option value="XOF">West African CFA (XOF)</option>
<option value="WDC">WorldCoin (WDC)</option>
<option value="YAC">Yacoin (YAC)</option>
<option value="YER">Yemeni Rial (YER)</option>
<option value="ZMW">Zambian Kwacha (ZMW)</option>
<option value="ZEC">Zcash (ZEC)</option>
<option value="ZTC">Zeitcoin (ZTC)</option>
<option value="ZET">Zetacoin (ZET)</option>
</select>
</td></tr><tr><td>
</td><td>
<input type="submit" id="submit" name="submit" value="Convert">
</td></tr></table>
</form>
